# Generated by Django 3.2.8 on 2021-10-13 23:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='document',
            name='name',
        ),
        migrations.AddField(
            model_name='document',
            name='body',
            field=models.TextField(default='default body', verbose_name='Document body'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='document',
            name='title',
            field=models.CharField(default='default title', max_length=100, verbose_name='Document title'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='topic',
            name='long_desc',
            field=models.TextField(default='long desc', verbose_name='long description'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='topic',
            name='short_desc',
            field=models.CharField(default='short desc', max_length=150, verbose_name='short description'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='topic',
            name='name',
            field=models.CharField(max_length=50),
        ),
    ]
