# Generated by Django 3.2.8 on 2021-10-13 23:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20211013_2304'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='file',
            field=models.FileField(default='Nadda', upload_to='documents/', verbose_name='Document upload'),
            preserve_default=False,
        ),
    ]
