# Generated by Django 3.2.8 on 2021-10-14 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_auto_20211014_1252'),
    ]

    operations = [
        migrations.RenameField(
            model_name='document',
            old_name='body',
            new_name='raw_text',
        ),
        migrations.AlterField(
            model_name='document',
            name='file',
            field=models.FileField(blank=True, null=True, unique=True, upload_to='documents/', verbose_name='Document upload'),
        ),
    ]
